### ISSUE TITLE
Is it possible to provide a "Release date" for the tokens file?

### ISSUE THREAD

**Issue by tooomm** [Psithief/Cockatrice-tokens#2]
Thinking of it like a "last updated" kind of date.

It will fit perfectly with the "Edit sets" window and allow users to sort e.g. for newest sets on top by "Release date" without going to search for the tokens dummy set (TK) and manually add that back to the top.
Will help them to find out if there is already a newer set and they should check your git again to grab the newest one with tokens from the newest edition included as well!

**Comment by Psithief** [comment]
I don't understand what you're suggesting. I don't have anything to do with the tokens dummy set; not a single entry uses it. The tokens match the set order just the same as the cards do.

**Comment by Psithief** [comment]
I don't want to perpetuate `TK` and I don't want to overwrite its entry in `cards.xml` either because that's _rude_. :grinning:

**Comment by tooomm** [comment]
Totally forgot about this issue... I might have been a bit unclear in my starting post as well.
Sorry about that!

I was referring to the "Release Date" in the `Edit sets...` dialog window in Cockatrice.
The "Dummy set containing tokens" shows none.
But I didn't know that this is part of the cards.xml file. I thought that you just need to add a date to your tokens.xml file and Cockatrice would read and display it there. My fault.

It is confusing anyway how the tokens work right now... took me quite a while to figure that out (and to understand your arguments)! lol
