### ISSUE TITLE
Latest token.xml wont load in cockatrice

### ISSUE THREAD

**Issue by poixen** [Psithief/Cockatrice-tokens#3]
The newest version of the token.xml file will not display anything in the cockatrice client. I have the Kiora vs Elspeth version loaded in now, that version seems to be working ok.

**Comment by Psithief** [comment]
Can you reproduce this on the latest weekly build (b840159) of Cockatrice? I can't.

**Comment by Psithief** [comment]
Can't reproduce issue.
