### ISSUE TITLE
some tokens use "TK" set

### ISSUE THREAD

**Issue by tooomm** [Psithief/Cockatrice-tokens#5]
They should use the corresponding sets they are printed in, instead the dummy token set.
Mixes displaying of tokens up a bit. I have the recent limited-legal sets (frf+dtk) and the dummy set for some custom stuff enabled. It shows me all tokens from the recent sets + my own **+ these 3 unrelated tokens**: (because they are linked to the dummy TK set in your file)
- [**Hippo**](http://img.photobucket.com/albums/v18/qtinator/Hippo.jpg)
- [**Squirrel**](http://img.photobucket.com/albums/v202/zcorpion/mtg/Squirrel_token.jpg)
- [**Insect** (with one space " ")](http://i167.photobucket.com/albums/u148/Ruja/Magic%20Tokens/Insect.jpg) / the pic is from *Commander* set (CMD from June, 2011)

I don't know the exact sets symbols of the Hippo and Squirrel token though... maybe someone else does? Squirrel might be some judge promo stuff.

<br>
Sources (not all links show all sets):
- http://magic.wizards.com/en/game-info/products/card-set-archive
- http://mtg.wikia.com/wiki/Set
- http://en.wikipedia.org/wiki/List_of_Magic:_The_Gathering_sets

**Comment by Psithief** [comment]
Ugh, I thought I deleted all the tokens from that 'set'. :-1:
I hate that dummy set.

**Comment by tooomm** [comment]
we get that sorted out ;)

you have a clue about the hippo and squirrel token? which set are they from?

**Comment by Psithief** [comment]
* Hippos are made by [Pheldagriff / Questing Pheldagriff](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&text=+[hippo]+[token]). I'm writing the set as `ALL` for alliances.
* That insect is not a real token, as tokens were not printed for that set. Now that there is an official token for it, it can be replaced.
* The extra squirrel was cute but I don't want to support every legacy item now that customising cards has become easier.
