### ISSUE TITLE
Modern Master 2015 set uses wrong set code

### ISSUE THREAD

**Issue by tooomm** [Psithief/Cockatrice-tokens#6]
is: `MMB`
should be `MM2`

source:
- http://mtgsalvation.gamepedia.com/Modern_Masters_2015
- http://en.wikipedia.org/wiki/Modern_Masters

---

Edit: still seems to be unclear:
http://en.wikipedia.org/wiki/List_of_Magic:_The_Gathering_sets

let's wait and see

**Comment by Psithief** [comment]
[That source was different when I looked.](http://mtgsalvation.gamepedia.com/index.php?title=Modern_Masters_2015&diff=174938&oldid=174935) :+1:
